-- create your database schema using sql
-- Create the teams table
CREATE TABLE teams (
    team_id INTEGER PRIMARY KEY,
    full TEXT,
    team TEXT,
    nickname TEXT,
    city TEXT,
    [state] TEXT,
    founded INTEGER,
    division TEXT,
    conference TEXT
);

-- Create the players table with a foreign keys to the teams table
CREATE TABLE players (
    player_id INTEGER PRIMARY KEY,
    [first] TEXT,
    [last] TEXT,
    [name] TEXT,
    birthdate INTEGER,
    school TEXT,
    country TEXT,
    last_affiliation TEXT,
    height TEXT,
    height_inches INTEGER,
    [weight] INTEGER,
    season_exp INTEGER,
    jersey TEXT,
    pos TEXT,
    rosterstatus TEXT,
    from_year INTEGER,
    dleague_flag INTEGER,
    draft_year INTEGER,
    draft_round INTEGER,
    draft_number INTEGER,
    team_id INTEGER,
    team_id2 INTEGER,
    team TEXT,
    team2 TEXT,
    FOREIGN KEY (team_id) REFERENCES teams (team_id),
    FOREIGN KEY (team_id2) REFERENCES teams (team_id)
);
CREATE TABLE games (
    game_id INTEGER PRIMARY KEY,
    home TEXT,
    away TEXT,
    [date] DATE,
    home_pts INTEGER,
    away_pts INTEGER,
    min INTEGER,
    home_fgm INTEGER,
    home_fga INTEGER,
    home_fg_pct DECIMAL(5, 2),
    home_fg3m INTEGER,
    home_fg3a INTEGER,
    home_fg3_pct DECIMAL(5, 2),
    home_ftm INTEGER,
    home_fta INTEGER,
    home_ft_pct DECIMAL(5, 2),
    home_oreb INTEGER,
    home_dreb INTEGER,
    home_reb INTEGER,
    home_ast INTEGER,
    home_stl INTEGER,
    home_blk INTEGER,
    home_tov INTEGER,
    home_pf INTEGER,
    home_plus_minus INTEGER,
    away_fgm INTEGER,
    away_fga INTEGER,
    away_fg_pct DECIMAL(5, 2),
    away_fg3m INTEGER,
    away_fg3a INTEGER,
    away_fg3_pct DECIMAL(5, 2),
    away_ftm INTEGER,
    away_fta INTEGER,
    away_ft_pct DECIMAL(5, 2),
    away_oreb INTEGER,
    away_dreb INTEGER,
    away_reb INTEGER,
    away_ast INTEGER,
    away_stl INTEGER,
    away_blk INTEGER,
    away_tov INTEGER,
    away_pf INTEGER,
    away_plus_minus INTEGER,
    bubble BOOLEAN,
    [sample] BOOLEAN,
    season TEXT,
    FOREIGN KEY (home) REFERENCES teams (team)
    FOREIGN KEY (away) REFERENCES teams (team)
);
CREATE TABLE player_games (
    [name] TEXT,
    fgm INTEGER,
    fga INTEGER,
    fg_pct DECIMAL(5, 2),
    pts INTEGER,
    fg3m INTEGER,
    fg3a INTEGER,
    fg3_pct DECIMAL(5, 2),
    ftm INTEGER,
    fta INTEGER,
    ft_pct DECIMAL(5, 2),
    oreb INTEGER,
    dreb INTEGER,
    reb INTEGER,
    ast INTEGER,
    tov INTEGER,
    stl INTEGER,
    blk INTEGER,
    blka INTEGER,
    pf INTEGER,
    pfd INTEGER,
    min INTEGER,
    season TEXT,
    player_id INTEGER,
    pos TEXT,
    team TEXT,
    [date] DATE,
    game_id INTEGER,
    plus_minus INTEGER,
    dd2 BOOLEAN,
    [start] BOOLEAN,
    PRIMARY KEY (player_id, game_id)
    FOREIGN KEY (player_id) REFERENCES players (player_id)
    FOREIGN KEY (team) REFERENCES teams (team)
    FOREIGN KEY (game_id) REFERENCES games (game_id)
    FOREIGN KEY ([name]) REFERENCES players ([name])
);
